apiVersion: apps/v1
kind: Deployment
metadata:
  name: paiges-auth-api
  labels:
    app: paiges-auth-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paiges-auth-api
  template: 
    metadata:
      labels: 
        app: paiges-auth-api
    spec:
      containers:
        - name: paiges-auth-api
          image: paigesacr.azurecr.io/app1/paiges_external:2.0.RELEASE
          imagePullPolicy: Always
          ports:
            - containerPort: 8094
        - name: azure-pgbouncer-sidecar
          image: mcr.microsoft.com/azure-oss-db-tools/pgbouncer-sidecar:latest
          # Uncomment below if you always want the latest version
          # imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: configfiles
              mountPath: "/etc/pgbouncer"
              # writes update the secret, we do not want to do this
              readOnly: true  
          livenessProbe:
            tcpSocket:
              # This must match the port your applications use to talk to postgres
              port: 6432
            periodSeconds: 60
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "killall -INT pgbouncer && sleep 120"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ['all']
      volumes:
        - name: configfiles
          secret:
              # This must match the name of your secret above
              secretName: azure-pgbouncer-config
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: paiges-auth-api-loadbalancer-service
  labels:
    app: paiges-auth-api
spec:
  type: LoadBalancer #ClusterIP, #NodePort
  selector:
    app: paiges-auth-api
  ports:
    - name: http
      port: 80
      targetPort: 8094